### ISSUE TITLE
Exercise 4 - code formatting

### ISSUE THREAD

**Issue by mensur-durakovic** [ZJelic/oop-vjezbe#1]
Format your code properly, delete unecessarry empty lines and use proper intendations. Rest is ok 😉

**Comment by ZJelic** [comment]
Poštovani,

s obzirom da mi niste do sada slali mailove vezano uz vježbe i da sam
namjerno dodao više praznih linija zbog čitljivosti koda, moram li
ispraviti navedenu grešku i ostale greške i opet pushati vježbu na github?
Ili možda da to rješim kroz 5. vježbu?

Pozdrav,
Zvonimir Jelić

sub, 11. tra 2020. u 15:42 Mensur Duraković <notifications@github.com>
napisao je:

**Comment by mensur-durakovic** [comment]
Pozdrav,

jedna ili max dvije linije su dovoljne za razdvojiti neke logičke stvari od
ostatka, sve više od toga je nepotrebno.

S obzirom da je sve lijepo posloženo, volio bi da počistite i ostale vježbe
što se tiče formatiranje, uvlačenja i praznih linija. :)

LP,
Mensur
